#!/usr/bin/env python3

# Copyright (c) 2025 HomomorphicEncryption.org
# All rights reserved.
#
# This software is licensed under the terms of the Apache v2 License.
# See the LICENSE.md file for details.
#============================================================================

"""
Cleartext reference for the "AES Transciphering" workload.
For each test case:
    - Reads the dataset generated by generate_dataset.py
    - Re-encrypts it using aes library to sanity check
    - Decrypts the ciphertext using aes library to get the plaintext block(s)
    - Writes the result to expected_aes.txt
    - Computes and writes the expected mini-workload outputs
      (max_value.txt and inner_product.txt)
"""
import struct
import aes
from utils import parse_submission_arguments

def main():

    __, params, __, __, __ = parse_submission_arguments('Cleartext reference for the AES-transciphering FHE benchmark.')
    DATASET_PATH = params.datadir() / f"db.txt"
    DATASET_ENC_PATH = params.datadir() / f"db.hex"
    AES_KEY_PATH = params.datadir() / f"aes_key.hex"
    IV_PATH = params.datadir() / f"aes_iv.hex"
    OUT_PATH = params.datadir() / f"expected_aes.txt"
    MAX_PATH = params.datadir() / f"max_value.txt"
    IP_PATH = params.datadir() / f"inner_product.txt"

    with open(AES_KEY_PATH, "r") as f:
        aes_key = bytes.fromhex(f.read().strip())

    # 1) load dataset containing the encrypted AES block
    with open(DATASET_ENC_PATH, "r") as f:
        ciphertext_blocks = bytes.fromhex(f.read().strip())

    iv = None
    is_ctr_mode = (params.get_size() != 0)
    if is_ctr_mode:
        with open(IV_PATH, "r") as f:
            iv = bytes.fromhex(f.read().strip())

    # 2) Read the original dataset, encrypt it to sanity check it matches ciphertext
    with open(DATASET_PATH, "r") as f:
        db_ints = [int(line) for line in f.read().strip().split('\n') if line.strip()]
    packer = struct.Struct('>' + 'H' * params.get_db_bound())
    plaintext_blocks = packer.pack(*db_ints)
    
    test_encrypted = aes.encrypt(plaintext_blocks, aes_key, iv, is_ctr_mode)
    if bytes(test_encrypted) != ciphertext_blocks:
        print("Warning: Cleartext re-encryption doesn't match db.hex!")

    # 3) Decrypt using aes library
    decrypted_block = aes.decrypt(ciphertext_blocks, aes_key, iv, is_ctr_mode)

    # 4) Unpack the 16-byte blocks back into integers
    decrypted_bytes = bytes(decrypted_block)
    result = packer.unpack(decrypted_bytes)

    # 5) write to expected.txt (overwrites if it already exists)
    result = '\n'.join(str(value) for value in result)
    OUT_PATH.write_text(result + '\n', encoding="utf-8")

    # 6) Miniworkload #1: compute the maximum value in the decrypted database
    max_value = max(int(line) for line in result.split('\n') if line.strip())
    MAX_PATH.write_text(f"{max_value}\n", encoding="utf-8")

    # 7) Miniworkload #2: compute the inner product of the decrypted database with itself
    values = [int(line) for line in result.split('\n') if line.strip()]
    first_half = values[:len(values)//2]
    second_half = values[len(values)//2:len(values)]
    inner_product = sum((x*y) % (2**16) for x,y in zip(first_half, second_half)) % (2**16)
    IP_PATH.write_text(f"{inner_product}\n", encoding="utf-8")

    print(f"Cleartext implementation completed. Expected MAX: {max_value}, Expected IP: {inner_product}")


if __name__ == "__main__":
    main()